In [1]:
# Bullshit with matplotlib
import matplotlib
matplotlib.use('qt4agg')
import matplotlib.pyplot as plt

import numpy as np
from numpy import array, diag, sqrt, eye
from numpy.linalg import inv, eig, det
from scipy.linalg import sqrtm
import LinearSfeFunctions as sfe

In [2]:
def CostEllipse(C,ax):
    t_range = np.linspace(-np.pi,np.pi,77)
    circle = np.array([np.cos(t_range),np.sin(t_range)])
    ellipse = inv(sqrtm(C)) @ circle
    ax.plot(ellipse[0],ellipse[1])
    ax.set_aspect('equal')

In [3]:
def PlotEllipses(C,D,n,ax=None):
    if ax == None:
        fig, ax = plt.subplots()
    K = sfe.SymmetricLinearSFE(C,D,n)
    #TwoCostContours(C,inv(K),ax)
    CostEllipse(C,ax)
    CostEllipse(inv(K),ax)
    CostEllipse(inv(D),ax)
    plt.show()

In [5]:
def ShowMatrix(M,ax):
    CostEllipse(M,ax)
    e,E = eig(M)
    v = diag(1/sqrt(e)) @ E
    print(v)
    for i in range(2):
        x = [v[i,0], -v[i,0]]
        y = [-v[i,1], v[i,1]]
        ax.plot(x,y,'k--')

C = sfe.RandomPosDef()
fig, ax = plt.subplots()
ShowMatrix(C,ax)
plt.show()

[[ 0.60774803 -0.3640075 ]
 [ 1.04595675  1.74633259]]


In [6]:
def ShowMatrices(C,D,n,ax=None):
    if ax == None:
        fig, ax = plt.subplots()
    K = sfe.SymmetricLinearSFE(C,D,n)
    #TwoCostContours(C,inv(K),ax)
    ShowMatrix(C,ax)
    ShowMatrix(inv(K),ax)
    ShowMatrix(inv(D),ax)
    plt.show()

In [7]:
def PlotColumns(M,ax):
    # Plots the column vectors of 2xn matrix M on the axis ax
    for i in range(M.shape[1]):
        x = [0, M[i,0]]
        y = [0, M[i,1]]
        ax.plot(x,y)

In [13]:
# eyes
C = eye(2)
D = 1.1*eye(2)
ShowMatrices(C,D,2)

[[ 1.  0.]
 [ 0.  1.]]
[[ 0.79641191  0.        ]
 [ 0.          0.79641191]]
[[ 1.04880885  0.        ]
 [ 0.          1.04880885]]


In [15]:
# Independent goods

C = array([[2.0,0.0],[0.0,1.0]])
D = array([[1.0,0.0],[0.0,3.0]])
#fig, ax = plt.subplots()
#PlotEllipses(C,D,2,ax)
#PlotColumns(C,ax)
ShowMatrices(C,D,2)

[[ 0.70710678  0.        ]
 [ 0.          1.        ]]
[[ 0.60500033  0.        ]
 [ 0.          0.88954362]]
[[ 1.          0.        ]
 [ 0.          1.73205081]]


In [21]:
# Independent Costs; complements

C = array([[2.0,0.0],[0.0,1.0]])
D = array([[1.0,1.0],[1.0,3.0]])
ShowMatrices(C,D,1)
#PlotEllipses(C,D,3)
#PlotEllipses(C,D,7)

[[ 0.70710678  0.        ]
 [ 0.          1.        ]]
[[ 0.51166727  0.12078826]
 [-0.19543951  0.82789504]]
[[ 0.70710678  0.29289322]
 [-0.70710678  1.70710678]]


In [19]:
# Independent Costs; substitutes

C = array([[2.0,0.0],[0.0,1.0]])
D = array([[1.0,-1.0],[-1.0,3.0]])
PlotEllipses(C,D,2)
ShowMatrices(C,D,2)

[[ 0.70710678  0.        ]
 [ 0.          1.        ]]
[[ 0.56898756 -0.09372226]
 [ 0.14260322  0.86574374]]
[[ 0.70710678 -0.29289322]
 [ 0.70710678  1.70710678]]


In [20]:
# Independent Demand; economies of scope
C = array([[2.0,-1.0],[-1.0,1.0]])
D = array([[1.0,0.0],[0.0,3.0]])
fig, ax = plt.subplots()
PlotEllipses(C,D,2,ax)
e,E = eig(C)
X = sfe.DiagonalizingBasis(inv(C),D)
PlotColumns(inv(X),ax)

In [46]:
X @ D @ np.transpose(X)
inv(np.transpose(X)) @ C @ inv(X)

array([[  6.97224362e-01,   5.55111512e-16],
       [  8.88178420e-16,   4.30277564e+00]])

In [17]:
# Independent Demand; diseconomies of scope
C = array([[2.0,1.0],[1.0,1.0]])
D = array([[1.0,0.0],[0.0,3.0]])
PlotEllipses(C,D,2)